/**
 * Generates docs/RULES_INDEX.md from the rule registry (SPEC Appendix A).
 * Run: npx tsx scripts/gen-rules-index.ts  (or `npm run rules:index`)
 */
import { writeFileSync } from "node:fs";
import { RULES } from "../rules";

const rows = RULES.map((r) => `| \`${r.id}\` | ${r.title} | \`${r.source}\` | ${r.rationale} |`);
const md = `# Rules index

_Auto-generated by \`scripts/gen-rules-index.ts\` — do not edit by hand._

${RULES.length} rules registered in \`rules/index.ts\`.

| Id | Title | Source | Rationale |
|---|---|---|---|
${rows.join("\n")}
`;
writeFileSync(new URL("../docs/RULES_INDEX.md", import.meta.url), md);
console.log(`wrote docs/RULES_INDEX.md (${RULES.length} rules)`);
